//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutviewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sample
    {
        public int id { get; set; }
        public int typeid { get; set; }
        public float sampledata { get; set; }
        public System.DateTime sampledate { get; set; }
    
        public virtual sampletype sampletype { get; set; }
    }
}
